# Generated by Django 4.2.27 on 2026-01-30 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_reserva_a9955b_idx',
            old_name='payments_pa_reserva_0d100f_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_authori_d17c7e_idx',
            old_name='payments_pa_authori_c0e6e0_idx',
        ),
    ]
