# Generated by Django 4.2.21 on 2025-06-10 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_province_alter_city_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='province',
            name='is_active',
        ),
    ]
