"""
Django settings for project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import sys


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ct!8%zkethdsbc2zwd82((83#w#75ceqsy+8&(kw&nsnuak2sk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'accounts',
    'bus_companies',
    'fleet',
    'payments',
    'reservations',
    'routes',
    'seat',
    'city',
    'trips.apps.TripsConfig',

]



MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

WSGI_APPLICATION = 'backend.wsgi.application'

import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'postgres',
#         'USER': 'postgres.abxuvjwxbzcuozxqcvjl',
#         'PASSWORD': 'Lachin1404@urmia',
#         'HOST': 'aws-0-eu-central-1.pooler.supabase.com',
#         'PORT': '5432',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'BlitoDB',
        'USER': 'postgres',
        'PASSWORD': '1234',
        'HOST': 'db',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'accounts.CustomUser'

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10),  # توکن کوتاه‌عمر = امنیت بالا
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # برای auto login

#     'ROTATE_REFRESH_TOKENS': True,                   # هر بار رفرش شد، توکن جدید بسازه
#     'BLACKLIST_AFTER_ROTATION': True,                # قبلی رو غیرفعال کنه = امنیت بیشتر

#     'UPDATE_LAST_LOGIN': True,                       # زمان آخرین ورود رو به‌روز کنه

#     'ALGORITHM': 'HS256',
#     'SIGNING_KEY': SECRET_KEY,                       # استفاده از SECRET_KEY خود پروژه
#     'AUTH_HEADER_TYPES': ('Bearer',),                # نوع هدر برای درخواست‌ها

#     'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
#     'TOKEN_TYPE_CLAIM': 'token_type',
}



# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(BASE_DIR)


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# settings.py

# LANGUAGE_CODE = "fa-ir"
TIME_ZONE = "Asia/Tehran"
USE_I18N = True
USE_TZ = True

JAZZMIN_SETTINGS = {
    "site_title": "مدیریت بلیتو",
    "site_header": "پنل مدیریت بلیتو",
    "site_brand": "بلیتو",
    "welcome_sign": "خوش آمدید 👋",
    "site_logo": "images/logo.svg",
    "login_logo": "images/logo.svg",
    "site_logo_classes": "img-circle elevation-2",

    "changeform_format": "horizontal_tabs",
    "navigation_expanded": True,
    "hide_models": ["auth.Group"],

    "custom_css": "admin/custom.css",

    "icons": {
        "reservations.Reservation": "fas fa-ticket-alt",
        "seat.Seat": "fas fa-chair",
        "trips.Trip": "fas fa-bus",
        "routes.Route": "fas fa-route",
        "fleet.Fleet": "fas fa-shuttle-van",
        "payments.Payment": "fas fa-credit-card",
        "bus_companies.BusCompany": "fas fa-building",
        "city.City": "fas fa-city",
        "accounts.Profile": "fas fa-id-card",
        "auth.User": "fas fa-user",
    },
}




EMAIL_BACKEND = 'django.backend.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'blitocompany@gmail.com'
EMAIL_HOST_PASSWORD = 'uwzf oizm crnq lppj'  # App Password
DEFAULT_FROM_EMAIL = 'Belito <blitocompany@gmail.com>'

# EMAIL_BACKEND = 'django.backend.mail.backends.console.EmailBackend'
