# Generated by Django 4.2.21 on 2025-06-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'مسافر'), ('driver', 'راننده'), ('admin', 'مدیر')], default='customer', max_length=10, verbose_name='نقش کاربر'),
        ),
    ]
