# Generated by Django 4.2.21 on 2025-06-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_options_alter_profile_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='date_joiend',
            new_name='date_joined',
        ),
    ]
