# Generated by Django 4.2.21 on 2025-06-05 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_role'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet', to='accounts.profile', verbose_name='راننده'),
        ),
    ]
