# Generated by Django 4.2.21 on 2025-06-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_fleet_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleet',
            name='is_active',
        ),
    ]
