# Generated by Django 4.2.23 on 2025-08-14 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='total_price',
        ),
    ]
