# Generated by Django 4.2.21 on 2025-06-05 22:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bus_companies', '0004_alter_buscompanyrating_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=20, unique=True, verbose_name='شماره اتوبوس')),
                ('license_plate', models.CharField(max_length=15, unique=True, verbose_name='پلاک')),
                ('model', models.CharField(max_length=50, verbose_name='مدل')),
                ('brand', models.CharField(max_length=50, verbose_name='برند')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(1980)], verbose_name='سال تولید')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(10)], verbose_name='ظرفیت')),
                ('bus_type', models.CharField(choices=[('standard', 'معمولی'), ('luxury', 'لوکس'), ('vip', 'وی آی پی')], default='standard', max_length=20, verbose_name='نوع اتوبوس')),
                ('has_wifi', models.BooleanField(default=False, verbose_name=' وای فای')),
                ('has_ac', models.BooleanField(default=False, verbose_name='کولر')),
                ('has_tv', models.BooleanField(default=False, verbose_name='تلویزیون')),
                ('has_charging', models.BooleanField(default=False, verbose_name='شارژر')),
                ('has_blanket', models.BooleanField(default=False, verbose_name='پتو')),
                ('has_food_service', models.BooleanField(default=False, verbose_name='سرویس غذا')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fleet_images/', verbose_name='تصویر')),
                ('interior_image', models.ImageField(blank=True, null=True, upload_to='fleet_images/', verbose_name='تصویر داخلی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet', to='bus_companies.buscompany', verbose_name='شرکت اتوبوسرانی')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet', to=settings.AUTH_USER_MODEL, verbose_name='راننده')),
            ],
            options={
                'verbose_name': 'اتوبوس ناوگان',
                'verbose_name_plural': 'ناوگان اتوبوس\u200cها',
                'ordering': ['company', 'bus_number'],
            },
        ),
    ]
