# Generated by Django 4.2.21 on 2025-06-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_fleet_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
