# Generated by Django 4.2.21 on 2025-06-05 22:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bus_companies', '0003_buscompanyrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buscompanyrating',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='bus_companies.buscompany', verbose_name='شرکت اتوبوسرانی'),
        ),
        migrations.AlterField(
            model_name='buscompanyrating',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='امتیاز'),
        ),
        migrations.AlterUniqueTogether(
            name='buscompanyrating',
            unique_together={('user', 'company')},
        ),
    ]
