# Generated by Django 4.2.21 on 2025-06-09 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus_companies', '0004_alter_buscompanyrating_company_and_more'),
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_type', models.CharField(choices=[('standard', 'معمولی'), ('luxury', 'لوکس'), ('vip', 'وی آی پی')], max_length=20, verbose_name='نوع اتوبوس')),
                ('base_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت پایه')),
                ('distance_km', models.PositiveIntegerField(verbose_name='مسافت (کیلومتر)')),
                ('estimated_duration', models.DurationField(verbose_name='مدت زمان تقریبی سفر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_companies.buscompany', verbose_name='شرکت')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='city.terminal', verbose_name='مقصد')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='city.terminal', verbose_name='مبدا')),
            ],
            options={
                'verbose_name': 'مسیر',
                'verbose_name_plural': 'مسیرها',
                'ordering': ['origin', 'destination'],
                'unique_together': {('origin', 'destination', 'company', 'bus_type')},
            },
        ),
    ]
