# Generated by Django 4.2.21 on 2025-06-09 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0005_fleet_is_active'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_datetime', models.DateTimeField(verbose_name='زمان حرکت')),
                ('arrival_datetime', models.DateTimeField(verbose_name='زمان رسیدن')),
                ('current_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت فعلی')),
                ('status', models.CharField(choices=[('SCHEDULED', 'برنامه\u200cریزی شده'), ('BOARDING', 'در حال سوار شدن'), ('DEPARTED', 'حرکت کرده'), ('ARRIVED', 'رسیده'), ('CANCELLED', 'لغو شده')], default='SCHEDULED', max_length=20, verbose_name='وضعیت')),
                ('driver_name', models.CharField(max_length=100, verbose_name='نام راننده')),
                ('driver_phone', models.CharField(max_length=15, verbose_name='تلفن راننده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.fleet', verbose_name='اتوبوس')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route', verbose_name='مسیر')),
            ],
            options={
                'verbose_name': 'سفر',
                'verbose_name_plural': 'سفرها',
                'ordering': ['-departure_datetime'],
                'indexes': [models.Index(fields=['departure_datetime', 'status'], name='trips_trip_departu_98a42a_idx'), models.Index(fields=['route', 'departure_datetime'], name='trips_trip_route_i_56d567_idx')],
            },
        ),
    ]
