# Generated by Django 4.2.23 on 2025-08-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_driver_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='driver_phone',
        ),
    ]
