# Generated by Django 4.2.21 on 2025-06-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buscompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شرکت')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=15, verbose_name='تلفن')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='امتیاز')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='تعداد امتیازها')),
            ],
            options={
                'verbose_name': 'شرکت اتوبوسرانی',
                'verbose_name_plural': 'شرکت\u200cهای اتوبوسرانی',
            },
        ),
    ]
