# Generated by Django 4.2.21 on 2025-06-05 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buscompany',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='buscompany',
            name='rating_count',
        ),
    ]
