# Generated by Django 4.2.21 on 2025-06-05 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bus_companies', '0002_remove_buscompany_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusCompanyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='امتیاز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='bus_companies.buscompany', verbose_name='شرکت اتوبوسرانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'امتیازدهی به شرکت',
                'verbose_name_plural': 'امتیازدهی به شرکت\u200cها',
            },
        ),
    ]
