# Generated by Django 4.2.21 on 2025-06-09 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_rename_date_joiend_customuser_date_joined'),
        ('trips', '0002_alter_trip_driver_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField(verbose_name='شماره صندلی')),
                ('is_reserved', models.BooleanField(default=False, verbose_name='رزرو شده')),
                ('reserved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان رزرو')),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile', verbose_name='رزرو شده توسط')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='trips.trip')),
            ],
            options={
                'verbose_name': 'صندلی',
                'verbose_name_plural': 'صندلی\u200cها',
                'ordering': ['seat_number'],
                'indexes': [models.Index(fields=['trip', 'is_reserved'], name='seat_seat_trip_id_615360_idx')],
                'unique_together': {('trip', 'seat_number')},
            },
        ),
    ]
